### ISSUE TITLE
How to support chinease language?

### ISSUE THREAD

**Issue by Roddy1219** [mderasse/php-mpos#10]
Hello:
       How to support chinease language ?

**Comment by mderasse** [comment]
Hi / Nihao,

In Order to support a new language, you will need a translation tool such as poedit.
You will be able to import the tools/mpos.pot in it and start translating.

When you are done, add your translation in the locales directory (zh_CN), uncomment the language line in include/bootstrap.php (line 21).

**Comment by Roddy1219** [comment]
Hi:
    I generated.Mo files through tools. but Switching language is not effective.

**Comment by Roddy1219** [comment]
I need exec php composer.phar again?

**Comment by mderasse** [comment]
Did you also generate the .po ?

In order to make it work you also need to install php7.0-intl.

You will also need the locale on your system. On linux exec : locale -a to know if the local zh_CN is enable

Feel free to do a pullRequest  :)

**Comment by Roddy1219** [comment]
yes  make two file .mo and .po.

yes
root@localhost:/etc/php/7.0# locale -a
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX
zh_CN.utf8
zh_SG.utf8

**Comment by Roddy1219** [comment]
Hi. 
    I succeeded. Thank you very much！

**Comment by mderasse** [comment]
Will be great if you can share the translation :)

谢谢
